package org.example.project01lms.Mapper;

import org.example.project01lms.Dto.CustomerDto.CustomerCreationDto;
import org.example.project01lms.Dto.CustomerDto.CustomerUpdationDto;
import org.example.project01lms.Dto.CustomerDto.CustomerResponseDto;
import org.example.project01lms.Models.Customers;
import org.mapstruct.*;

import java.util.List;

@Mapper(componentModel = "spring") // use Spring injection
public interface CustomerMapper {

    @Mapping(target = "isActive", constant = "true")  // default active
    @Mapping(target = "libraryId", ignore = true)     // set manually in service
    @Mapping(target = "customerId", ignore = true)    // auto-generated by DB
    Customers toEntity(CustomerCreationDto dto);

    CustomerResponseDto toDto(Customers customers);

    List<CustomerResponseDto> toDtoList(List<Customers> customersList);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    void updateCustomerFromDto(CustomerUpdationDto dto, @MappingTarget Customers customers);
}
